#index:
#    path: /
#    controller: App\Controller\DefaultController::index

doc_url:
    path: /repo
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        path: 'https://github.com/EnricoBid/experimental-dashboard'
        permanent: true